[package]
name = "mcl-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.3"
strum = { version = "0.26.2", features = ["derive"] }
